name: testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-bats-versions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install bats
        run: npm install -g bats
      - name: run bats
        run: bats -v
      - name: install dependencies
        run: yarn install
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash
      # - name: build project
      #   run: npm run build
      # - name: build frontend
      #   run: |
      #     cd client
      #     yarn build
      - name: test-autograde
        # You may pin to the exact commit or the version.
        # uses: masaditya/test-autograde@f3040d06e4948cdf3648a5ee235c36561dc145ec
        uses: masaditya/test-autograde@v10.0
        with:
          # kelas yang diberikan tugas
          kelas: kelas yang diberikan tugas
          # tugas minggu ke
          minggu-ke: tugas minggu ke
