name: testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-bats-versions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install bats
        run: npm install -g bats
      - name: run bats
        run: bats -v
      - name: install dependencies
        run: yarn install
      # - name: build project
      #   run: npm run build
      # - name: build frontend
      #   run: |
      #     cd client
      #     yarn build
      - name: Trigger CircleCI Pipeline
        # You may pin to the exact commit or the version.
        # uses: CircleCI-Public/trigger-circleci-pipeline-action@21a9dd0f0ab137ed19dbf40f1e4faf634660e6ea
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.3
